### Pre Request
GET https://example.com

> {%
function getRandomNumber() {
  return Math.random() * 100;
}

client.global.set("boardName", getRandomNumber().toString());
client.global.set("listName", "A list");
%}

### Create board
POST {{trelloUrl}}{{trelloApiVersion}}/boards/?name={{boardName}}&key={{trelloKey}}&token={{trelloToken}}&defaultLists=false

{}

> {%
 client.test("Request executed successfully", function () {
   client.assert(response.status === 200, "Response status is not 200")
 });

 client.test("Board should be created", function () {
   client.assert(response.body.name === client.global.get("boardName"))
   client.assert(!response.body.closed)
 })

 client.test("Board should be private", function () {
   client.assert(response.body.prefs.permissionLevel === "private")
 })

client.global.set("boardId", response.body.id);
 %}

### Create Checklist
POST {{trelloUrl}}{{trelloApiVersion}}/lists?key={{trelloKey}}&token={{trelloToken}}&name={{listName}}&idBoard={{boardId}}

{}

> {%
client.test("Status code is 200", function () {
  client.assert(response.status === 200, "Response is not 200")
});

client.test("List should be created", function () {

  client.assert(response.body.name === client.global.get("listName"));
  client.assert(response.body.closed === false);
})

client.test("List was created inside the board", function () {
  client.assert(response.body.idBoard === client.global.get("boardId"));
})
 %}

### Delete board
DELETE {{trelloUrl}}{{trelloApiVersion}}/boards/{{boardId}}?key={{trelloKey}}&token={{trelloToken}}

> {%
 client.test("Status code is 200", function () {
  client.assert(response.status === 200, "Response is not 200")
});

 client.test("List was deleted", function () {
   client.assert(response.body._value === null);
 })

 client.global.clearAll();

 client.test("Board ID Cleared", function () {
   client.assert(client.global.get("boardId") === null || client.global.get("boardId") === undefined)
 })
 %}